px4_offboard:
  ros__parameters:
    polygon_center: [0, 0] # Центр многоугольника x,y в метрах 
    circum_radius: 50.0 # в метрах 
    n_sides: 10  #Количество сторон многоугольника 
    meter_per_sec: 50.0 # Расчетная ожидаемая скорость в м / с (может быть близко / меньше этого значения). Обратите внимание, что это всего лишь оценка, используемая только для установки количества уставок между вершинами. Это не фактический контроль скорости с обратной связью. 
    polygon_angle: 45 # в градусах (обратите внимание: держите 45 для квадрата.) 
    uav_height: -5.0 # в метрах. Должно быть отрицательным значением. 
    uav_yaw: 0.0 # в градусах
